# Generated by Django 2.2 on 2019-04-10 14:53

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(default=False, on_delete=django.db.models.fields.NOT_PROVIDED, related_name='replies', to='forum.Thread', verbose_name='Tópico'),
        ),
    ]
