# Generated by Django 2.2 on 2019-04-05 17:42

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
