# Generated by Django 2.1.7 on 2019-03-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190331_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=250, verbose_name='Descrição breve'),
        ),
    ]
