# Generated by Django 2.2 on 2019-04-06 19:02

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='materials', to='courses.Lesson', verbose_name='Aula'),
        ),
    ]
