# Generated by Django 2.1.7 on 2019-03-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190331_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=250, verbose_name='Descrição breve'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição completa'),
        ),
    ]
